# Generated by Django 2.0.10 on 2019-04-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='setting/')),
                ('tagline', models.CharField(max_length=50)),
                ('favicon', models.ImageField(blank=True, upload_to='setting/')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('seo', models.TextField(blank=True, max_length=200)),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('footerContent', models.TextField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
