# Generated by Django 2.0.10 on 2019-05-02 04:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20190424_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='footerContent',
            field=tinymce.models.HTMLField(),
        ),
    ]
