# Generated by Django 2.0.10 on 2019-04-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='image',
            field=models.ImageField(blank=True, upload_to='capability/'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='logo',
            field=models.ImageField(blank=True, upload_to='capability/'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
