# Generated by Django 2.0.10 on 2019-04-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capability', '0003_auto_20190420_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
